version: '3'

services:   
  web:
    container_name: web
    image: aimadjaouhar/org.pdfmaster:web-${version}
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro