version: '3'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080