version: '3'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared-net
  
  api:
    container_name: api
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - 3000
    networks:
      - shared-net

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - shared-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge