version: '3'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro