version: '3'

services:   
  web:
    container_name: web
    image: aimadjaouhar/org.pdfmaster:web-${version}
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared-net
  
  api:
    container_name: api
    image: aimadjaouhar/org.pdfmaster:web-${version}
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000
    networks:
      - shared-net
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge