name: org.pdfmaster CI

on:
  push:
    branches:
      - prod

  pull_request:
    branches:
      - prod

jobs:

  # build-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Extract version number
  #       run: |
  #         # Extract the version number
  #         commit_message=$(git log -1 --pretty=%B)

  #         version=$(echo "$commit_message" | grep -oP 'prod/v\K[0-9]+\.[0-9]+\.[0-9]+')

  #         echo "build version number: $version"
  #         echo "VERSION=$version" >> $GITHUB_ENV

  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
  #     - run: pnpm install
        
  #       name: Build nx project web
  #     - run: pnpm nx build web

  #       name: Set up QEMU
  #     - uses: docker/setup-qemu-action@v3
      
  #       name: Set up Docker Buildx
  #     - uses: docker/setup-buildx-action@v3
      
  #       name: Login to Docker Hub
  #     - uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
  #       name: Build and push web
  #     - uses: docker/build-push-action@v5
  #       with:
  #         context: "."
  #         file: ./docker/web.Dockerfile
  #         push: true
  #         tags: aimadjaouhar/org.pdfmaster:web-${{ env.VERSION }}
  
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: './terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: './terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2